version: "3.8"

services:
  gorest:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - dbdata:/var/lib/postgresql/dbdata

volumes:
  dbdata: # create the volume for persisting data.