# syntax=docker/dockerfile:1
FROM golang:1.17

ARG GOREST_POSTGRESS_USER
ARG GOREST_POSTGRESS_PASSWORD
ARG GOREST_POSTGRESS_NAME

ENV GOREST_POSTGRESS_USER "$GOREST_POSTGRESS_USER"
ENV GOREST_POSTGRESS_PASSWORD "$GOREST_POSTGRESS_PASSWORD"
ENV GOREST_POSTGRESS_NAME "$GOREST_POSTGRESS_NAME"

# Download Go modules
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download

# Copy the source code
COPY *.go ./

# Build
RUN go build -o /gorest
 
EXPOSE 8080
 
CMD ["/gorest"]